points:
  key:
    padding: cy
    footprints:
      choc_hotswap:
        type: choc
        anchor:
          rotate: 180
        params:
          hotswap: true
          reverse: true
          keycaps: true
        nets:
          from: GND
          to: =pin
      via_data:
        type: via
        anchor:
          shift: [0, -0.15cy]
        nets:
          net: =pin
      via_gnd:
        type: via
        anchor:
          shift: [0, -0.22cy]
        nets:
          net: GND
      led:
        type: led_sk6812
        params:
          reverse: true
          vias: true
        anchor:
          shift: [0, +0.25cy + 0.45]
        nets:
          GND: GND
          VCC: VCC
          DIN: D0
          DOUT: D0
  zones:
    matrix:
      anchor:
        rotate: 0
      columns:
        operation:
          rows:
            bottom:
              pin: B2
            home:
              pin: F0
            top:
              pin: F5
        pinky:
          stagger: 2
          spread: cx * 1.25 + 2
          rows:
            bottom:
              pin: F1
            home:
              pin: C7
            top:
              pin: F4
        ring:
          stagger: cy + 3
          rows:
            bottom:
              pin: D5
            home:
              pin: B7
            top:
              pin: B0
        middle:
          stagger: cy * 0.5
          rows:
            bottom:
              pin: B5
            home:
              pin: B4
            top:
              pin: D3
        index:
          stagger: -cy * 0.5
          rows:
            bottom:
              pin: E6
            home:
              pin: D7
            top:
              pin: D2
        inner:
          stagger: -2
          rows:
            bottom:
              pin: C6
            home:
              pin: D4
            top:
              pin: B6
      rows:
        bottom:
        home:
        top:
    thumbfan:
      anchor:
        ref: matrix_index_bottom
        shift: [-cx * 1.10, -25]
      columns:
        under:
          spread: 20
          key:
            pin: B3
        near:
          spread: cx
          rotate: -30
          origin: [-5, -15]
          key:
            pin: B1
        home:
          spread: cx * 1.2
          rotate: -10
          origin: [-10, 0]
          key:
            pin: F7
        far:
          spread: cx * 1.2
          rotate: -10
          origin: [-10, 0]
          key:
            pin: F6
      rows:
        thumb:

outlines:
  exports:
    raw:
      - type: polygon
        points:
          - ref: matrix_operation_top
            shift: [-0.75cx - 1, 0.5cy + 1]
          - ref: matrix_middle_top
            shift: [-0.5cx - 1, 0.5cy + 1]
          - ref: matrix_middle_top
            shift: [0.5cx + 1, 0.5cy + 1]
          - ref: matrix_inner_top
            shift: [1.5 cx + 8, 0.5cy + 1]
          - ref: matrix_inner_top
            shift: [1.5 cx + 8, -2.5cy + 1]
          - ref: thumbfan_far_thumb
            shift: [0.5cx + 2, 0.5cy]
          - ref: thumbfan_far_thumb
            shift: [0.5cx + 2, -0.5cy - 1]
          - ref: thumbfan_under_thumb
            shift: [0.5cx + 2, -0.5cy - 1]
          - ref: matrix_operation_bottom
            shift: [-0.75cx - 1, -0.7cy - 1]
    cutout:
      - type: outline
        name: raw
        fillet: 3
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
pcbs:
  main:
    outlines:
      main:
        outline: cutout
    footprints:
      elitec:
        type: elitec
        anchor:
          ref: matrix_inner_home
          shift: [cx * 1.2, cy * 0.5]
          rotate: 270
        params:
          orientation: down
      trrs:
        type: trrs
        anchor:
          ref: matrix_inner_bottom
          shift: [cx * 1.6, cy * 0.1]
          rotate: 270
        nets:
          A: GND
          B: GND
          C: D1
          D: VCC
        params:
          reverse: true
          symmetric: true
